pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'cd $WORKSPACE/pipeline/' && 'mvn -Denforcer.skip=true clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd $WORKSPACE/pipeline/' && 'mvn test -Denforcer.skip=true'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                 sh 'chmod +x ./jenkins/scripts/deliver.sh'
                 sh 'who am i'
                 sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
